name: Publish to npm

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm ci

      - name: Build the package
        run: npm run build
        
      - name: Print npm config
        run: npm config list

      - name: Publish to npm
        run: npm publish || echo "Publish failed with status $?"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
